# Generated by Django 3.2.6 on 2021-09-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
