# Generated by Django 3.2.6 on 2021-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitprofiles', '0003_alter_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
